### PR TITLE
[RC-906] initial update for Auto Registration

### PR DESCRIPTION
**Pull request by dolkein**
Initial update for review.  These scripts have been tested in prototype configuration.  The APIs are going to thru a parallel review and not deployed yet.  The next step is to deploy apv/latest and build a test package to integrate and verify functionality

### CODE REVIEW

**Comment by Digital-Larry** [comment]
/etc/connectd/services is only for interactive installer, so if the intent is to get rid of interactive installer then we don't need to keep that.

**Comment by dolkein** [comment]
Removing interactive installer is a potential future phase of auto registration.  First phase is to support cloning of the hardware and proper preparation of a RPi SD card

**Comment by dolkein** [comment]
I will leave this PR open during testing. Just need to get a package built to broader testing

**Comment by gbr-3068** [comment]
Noting that
1. Multiple CI failure show (3, 2 are hidden)
2. Of 14 commits on Aug 21, only 6 show Verified
3. Of 14 commits on Aug 21, only 11 show Green check mark

These should be resolved

**Comment by Digital-Larry** [comment]
The solution to the issue where the TESTPASSWORD CircleCI environment variable did not match the password of the test account is to set the TESTPASSWORD environment variable to the correct value.  This is not tracked in Github so there is no visibility that it has happened.

**Comment by gbr-3068** [comment]
I need a simple explanation not "set the TESTPASSWORD environment variable to the correct value."

If you are NOT going to do any more to resolve errors, please state:

"I will not resolve these errors, please approve as is"

**Comment by Digital-Larry** [comment]
Regarding "Verified" notification in the Github summary.  Apparently there is a way to add GPG signature verification to commits.  This will happen automatically to changes handled directly at Github, while some GPG key needs to be added to my remote command line environment.  I have never set that up, so my remote checkins have always lacked this key based certification.  I can add that going forward, but I don't see how to do it retroactively.

https://help.github.com/en/articles/managing-commit-signature-verification

**Comment by Digital-Larry** [comment]
The CircleCI TESTPASSWORD environment variable was corrected several months ago and subsequent tests have passed, or if they failed, it was for a different reason.

**Comment by gbr-3068** [comment]
For reference as to what is happening, here is the screen shot showing errors noted in https://github.com/remoteit/installer/pull/47#issuecomment-539624909
Screenshot 2019-10-05 11 45 02

**Comment by Digital-Larry** [comment]
Regarding the commits which did not run CI, such as the following:

image

I do not know why that happened.  Two subsequent commits did run and pass CI and so I am not going to ty to figure out why the previous ones did not run CI.  I am confident that the code which is being proposed to merge has passed CI and recommend that it be approved.

**Comment by Digital-Larry** [comment]
@gbr-3068 just "approve", I will handle "Squash and Merge".

**Pull request merged**
